pipeline{
    agent{
        label "slave1"
    }
    environment {
        Test = "test_value"
        Test1 = "test_value1"
    }
    stages{
        stage("Build"){
            steps{
                sh 'sleep 5'
                echo "========executing A========"
            }
        }
         stage("Test"){
            steps{
                sh '''
                set +x
                #!/bin/bash
                ls -lrt
                sleep 5
                '''
                echo "========executing A========"
            }
        }
         stage("Test1"){
            steps{
                sh '''
                #!/bin/bash
                ls -lrt
                sleep 10
                '''
                echo "========executing A========"
            }
        }
         stage("Test2"){
            steps{
                sh '''
                #!/bin/bash
                ls -lrt
                sleep 15
                set +x
                '''
                echo "========executing A========"
            }
        }
        
    }
}