pipeline{
    agent{
        label "node"
    }
    stages{
        stage("A"){
            steps{
                sh 'sleep 5'
                echo "========executing A========"
            }
        }
         stage("Test"){
            steps{
                sh '''
                #!/bin/bash
                ls
                sleep 5
                '''
                echo "========executing A========"
            }
        }
        
    }
}